export enum ActionTypes {
  FETCH_USERS = "FETCH_USERS",
  UPDATE_USERS = "UPDATE_USERS",
  FETCH_POSTS = "FETCH_POSTS",
  UPDATE_POSTS = "UPDATE_POSTS",
  FETCH_TODOS = "FETCH_TODOS",
  UPDATE_TODOS = "UPDATE_TODOS",
  MODAL_OPEN = "MODAL_OPEN",
  MODAL_CLOSE = "MODAL_CLOSE",
  LIMIT_REACHED = "LIMIT_REACHED",
}
